version: 2.1

orbs:
  go: circleci/go@2.2.5

jobs:
  build-and-test:
    docker:
      - image: cimg/go:1.24.1
    steps:
      - checkout
      - run: go mod tidy
      - run: go test ./...

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install gcloud CLI
          command: |
            # Disable prompts in gcloud installer
            export CLOUDSDK_CORE_DISABLE_PROMPTS=1

            # Install the Google Cloud SDK
            curl https://sdk.cloud.google.com | bash

            # Source for current shell
            source /home/circleci/google-cloud-sdk/path.bash.inc
            source /home/circleci/google-cloud-sdk/completion.bash.inc

            # Ensure future steps also have 'gcloud' in PATH
            echo "source /home/circleci/google-cloud-sdk/path.bash.inc" >> $BASH_ENV
            echo "source /home/circleci/google-cloud-sdk/completion.bash.inc" >> $BASH_ENV

            # Verify installation
            gcloud version

      # - run:
      #     name: Authenticate GCP Service Account
      #     command: |
      #       echo "$GOOGLE_SERVICE_ACCOUNT_KEY" > /tmp/account.json
      #       gcloud auth activate-service-account --key-file=/tmp/account.json
      #       gcloud config set project "$GCP_PROJECT_ID"
      - run:
          name: Authenticate GCP Service Account
          command: |
            echo "$GOOGLE_SERVICE_ACCOUNT_KEY" > /tmp/account.json
            gcloud auth activate-service-account --key-file=/tmp/account.json
            gcloud config set project "$GCP_PROJECT_ID"

      - run:
          name: Debug Authentication
          command: |
            echo "==== gcloud auth list ===="
            gcloud auth list
            echo "==== gcloud config list ===="
            gcloud config list

      - run:
          name: Enable Required APIs.
          command: |
            # Pre-enable APIs so we don't get prompts during deploy.
            # Adjust this list if you switch to Gen 2 or need additional services.
            gcloud services enable \
              cloudfunctions.googleapis.com \
              cloudresourcemanager.googleapis.com \
              run.googleapis.com \
              artifactregistry.googleapis.com \
              cloudbuild.googleapis.com \
              --project "$GCP_PROJECT_ID"
      - run:
          name: Debug Directory Structure
          command: |
            ls -R
      - run:
          name: List Deployment Files
          command: |
            echo "Listing files to be deployed:"
            find . -type f
      - run:
          name: Deploy Cloud Function
          command: |
            # Deploy a 1st Gen function (since we specify --no-gen2).
            gcloud functions deploy goCloudFunc \
              --region=us-central1 \
              --runtime go121 \
              --trigger-http \
              --allow-unauthenticated \
              --entry-point HelloWorld \
              --source . \
              --no-gen2 \
              --verbosity debug \
              --set-build-env-vars GOFLAGS="-buildvcs=false"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
