version: 2.1

orbs:
  go: circleci/go@2.2.5

jobs:
  build-and-test:
    docker:
      - image: cimg/go:1.24.1
    steps:
      - checkout
      - run: go mod tidy
      - run: go test ./...

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install gcloud CLI
          command: |
            # Disable prompts in gcloud installer
            export CLOUDSDK_CORE_DISABLE_PROMPTS=1

            # Install the Google Cloud SDK
            curl https://sdk.cloud.google.com | bash

            # For this current step, source so 'gcloud' is immediately available
            source /home/circleci/google-cloud-sdk/path.bash.inc
            source /home/circleci/google-cloud-sdk/completion.bash.inc

            # Ensure future steps also have 'gcloud' on PATH by writing to $BASH_ENV
            echo "source /home/circleci/google-cloud-sdk/path.bash.inc" >> $BASH_ENV
            echo "source /home/circleci/google-cloud-sdk/completion.bash.inc" >> $BASH_ENV

            # Optional: verify installation in this same step
            gcloud version

      - run:
          name: Authenticate GCP Service Account
          command: |
            echo "$GOOGLE_SERVICE_ACCOUNT_KEY" > /tmp/account.json
            gcloud auth activate-service-account --key-file=/tmp/account.json
            gcloud config set project "$GCP_PROJECT_ID"

      - run:
          name: Deploy Cloud Function
          command: |
            gcloud functions deploy goCloudFunc \
              --region=us-central1 \
              --runtime go123 \
              --trigger-http \
              --allow-unauthenticated \
              --entry-point HelloWorld \
              --source . \
              --no-gen2

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
